# user code for interacting with server
import socket


# establish tcp connection to server
# takes in server ip and port number
# return socket object
def Connect(serverIP, port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((serverIP, port))
    return s


# send ready message to server
# takes in socket object and player name
# return true if server responds with 1 (everything is good)
# return false otherwise
def Client_Ready(s, pname):
    s.send("Client_Ready," + pname.encode())
    data = s.recv(1024).decode("utf-8")
    if data == "1":
        return True
    else:
        return False


# check to see if box is available
# takes in socket object and box number
# return true if server responds with 1 (box is available)
# return false otherwise
def Request_Box(s, box_Num):
    msg = f"Request_Box,{box_Num}"
    s.send(msg.encode("utf-8"))
    data = s.recv(1024).decode("utf-8")
    if data == "1":
        return True
    else:
        return False

# check to see if we have this box
# takes in socket object and box number
# return true if server responds with 1 (we have this box)
# return false otherwise
def Have_Box(s, box_Num):
    msg = f"Have_Box,{box_Num}"
    s.send(msg.encode("utf-8"))
    data = s.recv(1024).decode("utf-8")
    if data == "1":
        return True
    else:
        return False

# Guess
# takes in socket object, player's guess and box number
# return true if server responds with 1 (guess is correct)
# return false otherwise
def Guess(s, box_Num, guess):
    msg = f"Guess,{box_Num},{guess}"
    s.send(msg.encode("utf-8"))
    data = s.recv(1024).decode("utf-8")
    if data == "1":
        return True
    else:
        return False


# Request update
# takes in socket object
# return server response
def Request_State(s):
    msg = f"Request_State"
    s.send(msg.encode("utf-8"))
    data = s.recv(1024).decode("utf-8").split(",")
    len = int(data[0])
    client_cnt = int(data[1])
    data = data[2:]
    states = []
    for i in range(len + 1):
        states.append((int(data[3 * i]), data[3 * i + 1], int(data[3 * i + 2])))

    return (len, client_cnt, states)


# get word
# takes in socket object
# return the random word generated by the server
def Get_Word(s):
    msg = f"Get_Word"
    s.send(msg.encode("utf-8"))
    data = s.recv(1024).decode("utf-8")
    return data


# unlock_box
# takes in socket object
# does not return anything. to unlock any locks held by a player
def Unlock_Box(s):
    msg = f"Unlock_Box"
    s.send(msg.encode("utf-8"))


# Disconnect
# takes in socket object
# no return value, closes socket to server
def Disconnect(s):
    s.close()
    return
